# Generated by Django 3.0.13 on 2021-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210309_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='designed_link',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Designed Link'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Short_link'),
        ),
    ]
